### ISSUE TITLE
Add docs for basic client functionality

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernanalysispreservation/cap-client#32]

**Comment by tiborsimko** [comment]
... and plug it to ReadTheDocs (and add a usage example to CAP's own documentation).

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko  first version of docs http://cap-client-test.readthedocs.io/en/latest/ . Please check it out, any feedback would be perfect :)

**Comment by tiborsimko** [comment]
Nice! Some comments:

- Copyright is CERN, not individual persons.
- API section in RTFD docs are usually reserved for something like Pythonic API; it may be confusing to users to see CLI API there.  Basically, what you have right now in the API section, is more of the "User guide" or "Tutorial" or "Getting started" type of material.  Perhaps move it there, and make everything on the single page, since we don't need separate chapters for "tiny" client yet?
- If we don't go for "single page" layout, but "chaptered layout", we should put also "how to contribute" and other sections. You can look at *nascent* REANA client, we could keep consistent organisation harmony between the two clients https://reana-client.readthedocs.io/
- It would be good to put up a nice README on GitHub for those people that hit this first.  Such as README could be reused for RTFD chapters, as we do it for Invenio. See some examples like https://github.com/dib-lab/osf-cli 
- Have you generated these docs from the cap-client repository reusing docstrings?  E.g. there is no "docs" directory in the repository for Sphinx...

Anyway it'll be better/faster to discuss these live when we meet... this was just some raw brain dump upon seeing this test version.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko nope it wasn't generated using docstrings, we wrote it manually and we build the basic structure of ```docs``` folder by running ```sphinx-quickstart``` which more or less works as a cookie cutter.
